/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentSystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carlj
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutuS
     */
    public AboutUs() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("About Us");
        try{
           Image image = new ImageIcon("bsulogo.png").getImage();
           this.setIconImage(image);
          }catch(Exception e){
              System.out.println("Appilcation icon not found");
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        instucLabel = new javax.swing.JLabel();
        surNameNierra = new javax.swing.JLabel();
        roleNierra = new javax.swing.JLabel();
        presentedLabel = new javax.swing.JLabel();
        submitLabel = new javax.swing.JLabel();
        profEvyLabel = new javax.swing.JLabel();
        nameNierra = new javax.swing.JLabel();
        sectionNierra = new javax.swing.JLabel();
        surLabelSantoyo = new javax.swing.JLabel();
        nameLabelSantoyo = new javax.swing.JLabel();
        sectionSantoyo = new javax.swing.JLabel();
        roleSantoyo = new javax.swing.JLabel();
        surNameDeGuzman = new javax.swing.JLabel();
        nameDegUZMAN = new javax.swing.JLabel();
        SECTIONdEgUZMAN = new javax.swing.JLabel();
        roleDeGuzman = new javax.swing.JLabel();
        surNameReyes = new javax.swing.JLabel();
        naemReyes = new javax.swing.JLabel();
        sectionReyes = new javax.swing.JLabel();
        roleReyes = new javax.swing.JLabel();
        surNamePonti = new javax.swing.JLabel();
        namePonti = new javax.swing.JLabel();
        sectionPonti = new javax.swing.JLabel();
        rolePonti = new javax.swing.JLabel();
        surNameInahro = new javax.swing.JLabel();
        nameInahro = new javax.swing.JLabel();
        sectionInahro = new javax.swing.JLabel();
        roleInahro = new javax.swing.JLabel();
        facePonti = new javax.swing.JLabel();
        faceSantoyo = new javax.swing.JLabel();
        faceReyes = new javax.swing.JLabel();
        faceDeGuzman = new javax.swing.JLabel();
        faceInahro = new javax.swing.JLabel();
        faceBernie = new javax.swing.JLabel();
        blackPanel = new javax.swing.JPanel();
        orangePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        titleLabel.setText("Final Project in Human-Computer Intraction");
        backPanel.add(titleLabel);
        titleLabel.setBounds(60, 10, 379, 40);

        instucLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        instucLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instucLabel.setText("Instructor");
        backPanel.add(instucLabel);
        instucLabel.setBounds(210, 100, 160, 40);

        surNameNierra.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surNameNierra.setText("Nierra, ");
        backPanel.add(surNameNierra);
        surNameNierra.setBounds(180, 610, 90, 40);

        roleNierra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roleNierra.setText("Slight Programmer, Laptop Provider, Cook");
        backPanel.add(roleNierra);
        roleNierra.setBounds(100, 650, 290, 40);

        presentedLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        presentedLabel.setText("Presented to :");
        backPanel.add(presentedLabel);
        presentedLabel.setBounds(110, 70, 100, 40);

        submitLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        submitLabel.setText("Submitted by:");
        backPanel.add(submitLabel);
        submitLabel.setBounds(90, 140, 100, 40);

        profEvyLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        profEvyLabel.setText("Engr. Evelyn C. Samson");
        backPanel.add(profEvyLabel);
        profEvyLabel.setBounds(210, 70, 160, 40);

        nameNierra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameNierra.setText("Bernie, S.");
        backPanel.add(nameNierra);
        nameNierra.setBounds(230, 610, 120, 40);

        sectionNierra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sectionNierra.setText("ACT 2I-G1");
        backPanel.add(sectionNierra);
        sectionNierra.setBounds(200, 630, 70, 40);

        surLabelSantoyo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surLabelSantoyo.setText("Santoyo, ");
        backPanel.add(surLabelSantoyo);
        surLabelSantoyo.setBounds(160, 170, 70, 40);

        nameLabelSantoyo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameLabelSantoyo.setText("Krishield Kyle, S.");
        backPanel.add(nameLabelSantoyo);
        nameLabelSantoyo.setBounds(220, 170, 120, 40);

        sectionSantoyo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sectionSantoyo.setText("ACT 2I-G1");
        backPanel.add(sectionSantoyo);
        sectionSantoyo.setBounds(200, 190, 70, 40);

        roleSantoyo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roleSantoyo.setText("Programmer, Designer");
        backPanel.add(roleSantoyo);
        roleSantoyo.setBounds(170, 210, 150, 40);

        surNameDeGuzman.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surNameDeGuzman.setText("De Guzman,");
        backPanel.add(surNameDeGuzman);
        surNameDeGuzman.setBounds(150, 260, 90, 40);

        nameDegUZMAN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameDegUZMAN.setText("Carl Justine, M.");
        backPanel.add(nameDegUZMAN);
        nameDegUZMAN.setBounds(240, 260, 120, 40);

        SECTIONdEgUZMAN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        SECTIONdEgUZMAN.setText("ACT 2I-G1");
        backPanel.add(SECTIONdEgUZMAN);
        SECTIONdEgUZMAN.setBounds(200, 280, 70, 40);

        roleDeGuzman.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roleDeGuzman.setText("Programmer, Designer");
        backPanel.add(roleDeGuzman);
        roleDeGuzman.setBounds(170, 300, 150, 40);

        surNameReyes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surNameReyes.setText("Reyes,");
        backPanel.add(surNameReyes);
        surNameReyes.setBounds(160, 350, 90, 40);

        naemReyes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        naemReyes.setText("John Raineal, DJ.");
        backPanel.add(naemReyes);
        naemReyes.setBounds(210, 350, 120, 40);

        sectionReyes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sectionReyes.setText("ACT 2I-G1");
        backPanel.add(sectionReyes);
        sectionReyes.setBounds(200, 370, 70, 40);

        roleReyes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roleReyes.setText("Programmer, Designer");
        backPanel.add(roleReyes);
        roleReyes.setBounds(170, 390, 150, 40);

        surNamePonti.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surNamePonti.setText("Ponti, ");
        backPanel.add(surNamePonti);
        surNamePonti.setBounds(170, 440, 90, 40);

        namePonti.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namePonti.setText("Carlo Jesus, C.");
        backPanel.add(namePonti);
        namePonti.setBounds(210, 440, 120, 40);

        sectionPonti.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sectionPonti.setText("ACT 2I-G1");
        backPanel.add(sectionPonti);
        sectionPonti.setBounds(200, 460, 70, 40);

        rolePonti.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rolePonti.setText("Programmer");
        backPanel.add(rolePonti);
        rolePonti.setBounds(190, 480, 150, 40);

        surNameInahro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        surNameInahro.setText("Lopez, ");
        backPanel.add(surNameInahro);
        surNameInahro.setBounds(180, 530, 90, 40);

        nameInahro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nameInahro.setText("Jenaro, S.");
        backPanel.add(nameInahro);
        nameInahro.setBounds(230, 530, 120, 40);

        sectionInahro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sectionInahro.setText("ACT 2I-G1");
        backPanel.add(sectionInahro);
        sectionInahro.setBounds(200, 550, 70, 40);

        roleInahro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roleInahro.setText("Programmer");
        backPanel.add(roleInahro);
        roleInahro.setBounds(190, 570, 150, 40);

        facePonti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/pontiLogo.png"))); // NOI18N
        facePonti.setToolTipText("Carlo Ponti");
        backPanel.add(facePonti);
        facePonti.setBounds(30, 510, 110, 110);

        faceSantoyo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/sanLogo.png"))); // NOI18N
        faceSantoyo.setToolTipText("Krishield kyle Santoyo");
        backPanel.add(faceSantoyo);
        faceSantoyo.setBounds(20, 180, 110, 110);

        faceReyes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/reyesLogo.png"))); // NOI18N
        faceReyes.setToolTipText("John rainiel Reyes");
        backPanel.add(faceReyes);
        faceReyes.setBounds(20, 350, 110, 110);

        faceDeGuzman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/carlLogo.png"))); // NOI18N
        faceDeGuzman.setToolTipText("Carl justine De Guzman");
        backPanel.add(faceDeGuzman);
        faceDeGuzman.setBounds(370, 350, 110, 110);

        faceInahro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/jenLogo.png"))); // NOI18N
        faceInahro.setToolTipText("INAH <3 JENARO");
        backPanel.add(faceInahro);
        faceInahro.setBounds(370, 180, 110, 110);

        faceBernie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/logo.png"))); // NOI18N
        faceBernie.setToolTipText("Bernie Nierra");
        backPanel.add(faceBernie);
        faceBernie.setBounds(370, 510, 110, 110);

        blackPanel.setBackground(new java.awt.Color(0, 0, 0));
        backPanel.add(blackPanel);
        blackPanel.setBounds(0, 50, 370, 10);

        orangePanel.setBackground(new java.awt.Color(255, 102, 51));
        backPanel.add(orangePanel);
        orangePanel.setBounds(290, 60, 210, 10);

        getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 492, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SECTIONdEgUZMAN;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel blackPanel;
    private javax.swing.JLabel faceBernie;
    private javax.swing.JLabel faceDeGuzman;
    private javax.swing.JLabel faceInahro;
    private javax.swing.JLabel facePonti;
    private javax.swing.JLabel faceReyes;
    private javax.swing.JLabel faceSantoyo;
    private javax.swing.JLabel instucLabel;
    private javax.swing.JLabel naemReyes;
    private javax.swing.JLabel nameDegUZMAN;
    private javax.swing.JLabel nameInahro;
    private javax.swing.JLabel nameLabelSantoyo;
    private javax.swing.JLabel nameNierra;
    private javax.swing.JLabel namePonti;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JLabel presentedLabel;
    private javax.swing.JLabel profEvyLabel;
    private javax.swing.JLabel roleDeGuzman;
    private javax.swing.JLabel roleInahro;
    private javax.swing.JLabel roleNierra;
    private javax.swing.JLabel rolePonti;
    private javax.swing.JLabel roleReyes;
    private javax.swing.JLabel roleSantoyo;
    private javax.swing.JLabel sectionInahro;
    private javax.swing.JLabel sectionNierra;
    private javax.swing.JLabel sectionPonti;
    private javax.swing.JLabel sectionReyes;
    private javax.swing.JLabel sectionSantoyo;
    private javax.swing.JLabel submitLabel;
    private javax.swing.JLabel surLabelSantoyo;
    private javax.swing.JLabel surNameDeGuzman;
    private javax.swing.JLabel surNameInahro;
    private javax.swing.JLabel surNameNierra;
    private javax.swing.JLabel surNamePonti;
    private javax.swing.JLabel surNameReyes;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
