/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentSystem;

import static EnrollmentSystem.Main.index;
import static EnrollmentSystem.Variables.StudFullName;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carlj
 */
public class Diploma extends javax.swing.JFrame {

    /**
     * Creates new form Diploma
     */
    public Diploma() {
        initComponents();
        this.setTitle("Diploma");
        this.setLocationRelativeTo(null);
        
        nameL.setText(StudFullName.get(index)+"");
         try{
           Image image = new ImageIcon("bsulogo.png").getImage();
           this.setIconImage(image);
          }catch(Exception e){
              System.out.println("Appilcation icon not found");
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        repPhLabel = new javax.swing.JLabel();
        cityMalLabel = new javax.swing.JLabel();
        BSULabel = new javax.swing.JLabel();
        assLabel = new javax.swing.JLabel();
        logoBSU = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 248, 190));
        jPanel1.setLayout(null);

        repPhLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        repPhLabel.setText("Republic of the Philippines");
        jPanel1.add(repPhLabel);
        repPhLabel.setBounds(420, 20, 155, 16);

        cityMalLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cityMalLabel.setText("City of Malolos");
        jPanel1.add(cityMalLabel);
        cityMalLabel.setBounds(450, 60, 155, 16);

        BSULabel.setFont(new java.awt.Font("Cloister Black", 0, 22)); // NOI18N
        BSULabel.setText("Bulacan State University");
        jPanel1.add(BSULabel);
        BSULabel.setBounds(390, 30, 241, 38);

        assLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        assLabel.setText("DIPLOMA");
        jPanel1.add(assLabel);
        assLabel.setBounds(450, 90, 188, 26);

        logoBSU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/bsulogoSmall.png"))); // NOI18N
        jPanel1.add(logoBSU);
        logoBSU.setBounds(300, 20, 70, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/pirma.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 510, 150, 90);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Nierra, Berrniee, W");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 570, 240, 19);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Ethics Teacher");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 590, 150, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/pirma2.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(850, 500, 100, 90);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Lopez, Jenarlie, X.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(830, 570, 150, 19);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Head of Justice");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(840, 580, 150, 30);

        nameL.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jPanel1.add(nameL);
        nameL.setBounds(450, 170, 510, 50);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setText("This is to certify that");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 180, 340, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel8.setText("has finished the 2 year course of Associate in");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 220, 780, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel9.setText("Communication in Technlogies in Bulacan State");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 270, 840, 30);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel10.setText("University on the 15th Day of June in the year 2017");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 310, 871, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/bulsuRed.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 100, 550, 490);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diploma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BSULabel;
    private javax.swing.JLabel assLabel;
    private javax.swing.JLabel cityMalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoBSU;
    private javax.swing.JLabel nameL;
    private javax.swing.JLabel repPhLabel;
    // End of variables declaration//GEN-END:variables
}
