/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author carlj
 */
public class EditFacProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditFacProfile
     */
    public EditFacProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Faculty Profile");
        
        //facIdField.setVisible(false);
        firstNameField.setVisible(false);
        lastNameField.setVisible(false);
        middleNameField.setVisible(false);
        facPassField.setVisible(false);
        idField.setVisible(false);
        saveBtn.setEnabled(false);
        facIdLabel.setText((String) Variables.ID.get(Variables.logmark));
        fullNameLabel.setText((String) Variables.name.get(Variables.logmark));
        String tempPass ="";
        int len = Variables.password.get(Variables.logmark).toString().length();
        for(int f=0; f<len; f++)
        {
            tempPass+="•";
        }
        facPassLabel.setText(tempPass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        studInfoLabel = new javax.swing.JLabel();
        blackPanelDesign = new javax.swing.JPanel();
        grayPanelDesign = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        facIdLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        facPassField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        facPassLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(null);

        studInfoLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        studInfoLabel.setText("Faculty Profile");
        backPanel.add(studInfoLabel);
        studInfoLabel.setBounds(10, 0, 220, 50);

        blackPanelDesign.setBackground(new java.awt.Color(0, 0, 0));
        backPanel.add(blackPanelDesign);
        blackPanelDesign.setBounds(0, 40, 430, 10);

        grayPanelDesign.setBackground(new java.awt.Color(255, 102, 51));
        backPanel.add(grayPanelDesign);
        grayPanelDesign.setBounds(350, 50, 320, 10);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Password:");
        backPanel.add(jLabel1);
        jLabel1.setBounds(10, 170, 100, 30);

        facIdLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(facIdLabel);
        facIdLabel.setBounds(110, 90, 90, 30);

        fullNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(fullNameLabel);
        fullNameLabel.setBounds(80, 130, 490, 30);

        middleNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(middleNameField);
        middleNameField.setBounds(420, 130, 150, 30);

        facPassField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        facPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facPassFieldActionPerformed(evt);
            }
        });
        backPanel.add(facPassField);
        facPassField.setBounds(100, 170, 240, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Name:");
        backPanel.add(jLabel4);
        jLabel4.setBounds(10, 130, 70, 30);

        lastNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(lastNameField);
        lastNameField.setBounds(80, 130, 150, 30);

        firstNameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(firstNameField);
        firstNameField.setBounds(250, 130, 150, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Faculty ID:");
        backPanel.add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 30);

        facPassLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backPanel.add(facPassLabel);
        facPassLabel.setBounds(100, 170, 270, 30);

        cancelBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        backPanel.add(cancelBtn);
        cancelBtn.setBounds(480, 230, 90, 23);

        saveBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        backPanel.add(saveBtn);
        saveBtn.setBounds(370, 230, 90, 23);

        editBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        backPanel.add(editBtn);
        editBtn.setBounds(250, 230, 100, 25);

        idField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idFieldKeyTyped(evt);
            }
        });
        backPanel.add(idField);
        idField.setBounds(110, 90, 150, 30);

        getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facPassFieldActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
       facIdLabel.setText("");
       fullNameLabel.setText("");
       facPassLabel.setText("");
       cancelBtn.setEnabled(false);
       saveBtn.setEnabled(true);
       idField.setVisible(true);
       firstNameField.setVisible(true);
       lastNameField.setVisible(true);
       middleNameField.setVisible(true);
       facPassField.setVisible(true);
       
       idField.setText((String)Variables.ID.get(Variables.logmark));
       firstNameField.setText((String)Variables.Fname.get(Variables.logmark));
       lastNameField.setText((String)Variables.Lname.get(Variables.logmark));
       middleNameField.setText((String)Variables.Mname.get(Variables.logmark));
       facPassField.setText((String)Variables.password.get(Variables.logmark));
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if(idField.getText().equals("")||
           lastNameField.getText().equals("")||
           firstNameField.getText().equals("")||
           facPassField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please input all the needed informations","Edit Faculty Profile", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
              int ctr=0;
                for(int x=0;x<Variables.ID.size();x++)
                {
                    if(x==Variables.logmark)
                    {
                        
                    }
                    else
                    {
                    if(idField.getText().equals(Variables.ID.get(x)))
                    ctr=1;
                    }
                }

                if(ctr==1)
                {
                    ctr=0;
                    //Login.AddFaculty.add(num);
                    JOptionPane.showMessageDialog(null,"Already Used ID","",JOptionPane.INFORMATION_MESSAGE);
                    //facultyNum.setText("");
                    //facultyNum.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, new java.awt.Color(255, 0, 0)));
                }
                else
                {
        String lname = lastNameField.getText();
        String fname = firstNameField.getText();
        String mname = middleNameField.getText();
//        int ctr=0;
//                for(int x=0;x<Login.ID.size();x++)
//                {
//                    if(facIdField.getText().equals(Login.ID.get(x)))
//                    if(x==Login.logmark)
//                    {
//                        ctr=0;
//                    }
//                    else
//                    {
//                    ctr=1;
//                    }
//                }
//
//                if(ctr==1)
//                {
//                    ctr=0;
//                    JOptionPane.showMessageDialog(null,"Already Used ID","",JOptionPane.INFORMATION_MESSAGE);
//                    //facIdField.setText("");
//                }
//       else
//                {
        String l= lname.trim();
        String f= fname.trim();
        String m= mname.trim();
        
        String lastName = ""; 
        String firstName = ""; 
        String middleName = "";
        if(m.equals(""))
        {
            middleName="*";
        }
        else
        {
        if(m.contains("."))
        {
          String toUp =m.toUpperCase();
          int len = toUp.length();
          String midName = toUp.charAt(0)+"";
           for(int x=0; x<len; x++)
           {
               try
               {
               if(toUp.charAt(x)=='.')
               {
                   midName += toUp.charAt(x+1);
               }
               }
               catch(Exception e)
               {
                   
               }
           }
           midName.replaceAll(" ", "");
           midName+=".";
           middleName = midName;
        }
        else if(m.contains(" "))
        {
            
            String toUp = m.toUpperCase();
            int len = toUp.length();
            String mid = toUp.charAt(0)+"";
            for(int x=0; x<len; x++)
            {
                if(toUp.charAt(x)==' ')
                {
                    mid+=toUp.charAt(x+1);
                }
            }
            mid+=".";
            mid.replaceAll(" ", "");
            middleName = mid;
        }
        
        else
        {
             char startM;
             int lenM=0;
             String upM = m.toUpperCase();
             startM = upM.charAt(0);
             lenM = m.length();
             String lastM = m.substring(1, lenM);
             middleName = startM+". ";
             
        }
        }
        char startL;
        char startF;
        //char startM;
        
        int lenL=0;
        int lenF=0;
        //int lenM=0;
        
        String upL = l.toUpperCase();
        startL = upL.charAt(0);
        
        String upF = f.toUpperCase();
        startF = upF.charAt(0);
        
        //String upM = m.toUpperCase();
        //startM = upM.charAt(0);
      
        String lowL = l.toLowerCase();
        String lowF = f.toLowerCase();
        String lowM = m.toLowerCase();
        
        lenL = l.length();
        lenF = f.length();
        //lenM = m.length();
        
        String lastL = lowL.substring(1, lenL);
        String lastF = lowF.substring(1, lenF);
        //String lastM = m.substring(1, lenM);
        
        lastName = startL+lastL; 
        firstName = startF+lastF; 
        //middleName = startM+". "; 
        
        if(lastName.contains(" "))
        {
            int len = lastName.length();
            for(int x=0; x<len; x++)
            {
                if(lastName.charAt(x)==' ')
                {
                   String rep = " "+lastName.charAt(x+1);
                   String repp = rep.toUpperCase();
                   String temp = lastName.replace(rep,repp);
                   lastName = temp;
                }
            }
        }
            if(firstName.contains(" "))
        {
            int len = firstName.length();
            for(int x=0; x<len; x++)
            {
                if(firstName.charAt(x)==' ')
                {
                   String rep = " "+firstName.charAt(x+1);
                   String repp = rep.toUpperCase();
                   String temp = firstName.replace(rep,repp);
                   firstName = temp;
                }
            }
        }
                    System.out.println("FIrst Name: "+firstName);
            String fullname = lastName+", "+firstName+", "+middleName;
//            String copylast = lastName+", ", copyfirst= firstName+", ", copyMid=middleName;
//            String fullname =copylast+copyfirst+copyMid;
            
            System.out.println("Datamark: "+Variables.datamark);
            Variables.name.set(Variables.logmark, lastName+", "+firstName+", "+middleName);
            Variables.Fname.set(Variables.logmark, firstName);
            Variables.Lname.set(Variables.logmark, lastName);
            Variables.Mname.set(Variables.logmark, middleName);
            Variables.password.set(Variables.logmark, facPassField.getText().toString());
            Variables.ID.set(Variables.logmark,idField.getText().toString());
            Main.facNumLabel.setText((String) Variables.ID.get(Variables.logmark));
            idField.setVisible(false);
            firstNameField.setVisible(false);
            lastNameField.setVisible(false);
            middleNameField.setVisible(false);
            facPassField.setVisible(false);
            
            facIdLabel.setText((String) Variables.ID.get(Variables.logmark));
            fullNameLabel.setText((String) Variables.name.get(Variables.logmark));
            String tempPass ="";
            int len = Variables.password.get(Variables.logmark).toString().length();
            for(int ff=0; ff<len;ff++)
            {
               tempPass+="•";
            }
            facPassLabel.setText(tempPass);
            cancelBtn.setEnabled(true);
        }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void idFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFieldKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_idFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFacProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFacProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFacProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFacProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFacProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel blackPanelDesign;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel facIdLabel;
    private javax.swing.JTextField facPassField;
    private javax.swing.JLabel facPassLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JPanel grayPanelDesign;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel studInfoLabel;
    // End of variables declaration//GEN-END:variables
}
