/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentSystem;

import static EnrollmentSystem.AssesmentPaper.totalUnits;
import static EnrollmentSystem.EvalForm.rowCopy;
import static EnrollmentSystem.EvalForm.units;
import static EnrollmentSystem.Main.viewStudRecords;
import static EnrollmentSystem.Variables.StudFullName;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author carlj
 */
public class Reciept extends javax.swing.JFrame {

    /**
     * Creates new form Reciept
     */
    public Reciept() {
        initComponents();
        this.setLocationRelativeTo(null);
//         scholarPayment = AssesmentPaper.first+AssesmentPaper.second;
//                meth="Promisory";
//                payment=total;
//                change = total - AssesmentPaper.first+AssesmentPaper.second;
        
        payorLabel.setText((String) StudFullName.get(Main.marker));
       
        String copy=EvalForm.units+"";
        
        feeP.setLayout(new GridLayout(14,1));
        feeP.add(new JLabel("Registration Fee"));
        feeP.add(new JLabel("Library Fee"));
        feeP.add(new JLabel("Medical Dental Fee"));
        feeP.add(new JLabel("School Paper"));
        feeP.add(new JLabel("SCUAA Fee"));
        feeP.add(new JLabel("Student Government"));
        feeP.add(new JLabel("Socio Cultural Fee"));
        feeP.add(new JLabel("Athletic Fee"));
        feeP.add(new JLabel("Guidance Fee"));
        feeP.add(new JLabel("Security Fee"));
        feeP.add(new JLabel("Publication Fee"));
        feeP.add(new JLabel("Tuition Fee Regular"+"("+copy+"@200)"));
        feeP.add(new JLabel("PTA"));
        feeP.add(new JLabel("College Paper-CICT"));
        
        int asd=EvalForm.units;
        int mul=asd*200;
        String mulCopy=mul+"";
        int mes=67+117+54+28+133+28+67+133+41+41+41+100+30;
        priceP.setLayout(new GridLayout(14,1));
        priceP.add(new JLabel("67.00"));
        priceP.add(new JLabel("117.00"));
        priceP.add(new JLabel("54.00"));
        priceP.add(new JLabel("28.00"));
        priceP.add(new JLabel("133.00"));
        priceP.add(new JLabel("28.00"));
        priceP.add(new JLabel("67.00"));
        priceP.add(new JLabel("133.00"));
        priceP.add(new JLabel("41.00"));
        priceP.add(new JLabel("41.00"));
        priceP.add(new JLabel("41.00"));
        priceP.add(new JLabel(mulCopy+".00"));
        priceP.add(new JLabel("100.00"));
        priceP.add(new JLabel("30.00"));
        
      
         //meth = new JLabel(Cashier.meth);
         meth.setText(Cashier.meth);
       // String scholtot =Cashier.scholarPayment+"";
        //scholTot = new JLabel(Cashier.scholarPayment+"");
        scholTot.setText(Cashier.scholarPayment+"");
        //String pay = Cashier.payment+"";
        //payment = new JLabel(Cashier.payment+"");
        payment.setText(Cashier.payment+"");
        //String changes = Cashier.change+"";
        //change = new JLabel(Cashier.change+"");
        change.setText(Cashier.change+"");
        
        totalUnits = 0;
        rowCopy=0;
        units=0;
        viewStudRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        payorLabel = new javax.swing.JLabel();
        feeP = new javax.swing.JPanel();
        priceP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        meth = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scholTot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/bsulogoSmall.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 20, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnrollmentSystem/ReOfPh.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 80);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("REPUBLIC OF THE PHILIPPINES");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 180, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("OFFICIAL RECIEPT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 50, 120, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("BULACAN STATE UNIVERSITY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 70, 200, 17);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("PAYOR");

        payorLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(payorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 110, 430, 30);

        feeP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        feeP.setOpaque(false);

        javax.swing.GroupLayout feePLayout = new javax.swing.GroupLayout(feeP);
        feeP.setLayout(feePLayout);
        feePLayout.setHorizontalGroup(
            feePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        feePLayout.setVerticalGroup(
            feePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jPanel1.add(feeP);
        feeP.setBounds(20, 180, 290, 350);

        priceP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceP.setOpaque(false);

        javax.swing.GroupLayout pricePLayout = new javax.swing.GroupLayout(priceP);
        priceP.setLayout(pricePLayout);
        pricePLayout.setHorizontalGroup(
            pricePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        pricePLayout.setVerticalGroup(
            pricePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jPanel1.add(priceP);
        priceP.setBounds(310, 180, 100, 350);

        jLabel7.setText("NATURE OF COLLECTION");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 150, 140, 30);

        jLabel8.setText("AMOUNT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 160, 50, 14);

        change.setText("Change");
        jPanel1.add(change);
        change.setBounds(330, 570, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Payment");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 550, 70, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("TOTAL");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 530, 90, 30);

        payment.setText("Total");
        jPanel1.add(payment);
        payment.setBounds(330, 550, 80, 30);

        meth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meth.setText("meh");
        jPanel1.add(meth);
        meth.setBounds(150, 90, 110, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Change");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(280, 570, 50, 30);

        scholTot.setText("Total");
        jPanel1.add(scholTot);
        scholTot.setBounds(330, 530, 80, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel change;
    private javax.swing.JPanel feeP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel meth;
    public static javax.swing.JLabel payment;
    private javax.swing.JLabel payorLabel;
    private javax.swing.JPanel priceP;
    public static javax.swing.JLabel scholTot;
    // End of variables declaration//GEN-END:variables
}
